node {
        stage('clean-workspace') {
            cleanWs()
        }
        stage('launch-docker-container') {
            sh 'sudo docker run -d 8080:8080 --name: calculator joaodartora/calculator .'
        }
}